//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4_Tell.ws_3dCartApi {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://3dcart.com/", ConfigurationName="ws_3dCartApi.cartAPIAdvancedSoap")]
    public interface cartAPIAdvancedSoap {
        
        // CODEGEN: Generating message contract since element name storeUrl from namespace http://3dcart.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://3dcart.com/runQuery", ReplyAction="*")]
        _4_Tell.ws_3dCartApi.runQueryResponse runQuery(_4_Tell.ws_3dCartApi.runQueryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class runQueryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="runQuery", Namespace="http://3dcart.com/", Order=0)]
        public _4_Tell.ws_3dCartApi.runQueryRequestBody Body;
        
        public runQueryRequest() {
        }
        
        public runQueryRequest(_4_Tell.ws_3dCartApi.runQueryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://3dcart.com/")]
    public partial class runQueryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string storeUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sqlStatement;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string callBackURL;
        
        public runQueryRequestBody() {
        }
        
        public runQueryRequestBody(string storeUrl, string userKey, string sqlStatement, string callBackURL) {
            this.storeUrl = storeUrl;
            this.userKey = userKey;
            this.sqlStatement = sqlStatement;
            this.callBackURL = callBackURL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class runQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="runQueryResponse", Namespace="http://3dcart.com/", Order=0)]
        public _4_Tell.ws_3dCartApi.runQueryResponseBody Body;
        
        public runQueryResponse() {
        }
        
        public runQueryResponse(_4_Tell.ws_3dCartApi.runQueryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://3dcart.com/")]
    public partial class runQueryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement runQueryResult;
        
        public runQueryResponseBody() {
        }
        
        public runQueryResponseBody(System.Xml.Linq.XElement runQueryResult) {
            this.runQueryResult = runQueryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface cartAPIAdvancedSoapChannel : _4_Tell.ws_3dCartApi.cartAPIAdvancedSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class cartAPIAdvancedSoapClient : System.ServiceModel.ClientBase<_4_Tell.ws_3dCartApi.cartAPIAdvancedSoap>, _4_Tell.ws_3dCartApi.cartAPIAdvancedSoap {
        
        public cartAPIAdvancedSoapClient() {
        }
        
        public cartAPIAdvancedSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public cartAPIAdvancedSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public cartAPIAdvancedSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public cartAPIAdvancedSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _4_Tell.ws_3dCartApi.runQueryResponse _4_Tell.ws_3dCartApi.cartAPIAdvancedSoap.runQuery(_4_Tell.ws_3dCartApi.runQueryRequest request) {
            return base.Channel.runQuery(request);
        }
        
        public System.Xml.Linq.XElement runQuery(string storeUrl, string userKey, string sqlStatement, string callBackURL) {
            _4_Tell.ws_3dCartApi.runQueryRequest inValue = new _4_Tell.ws_3dCartApi.runQueryRequest();
            inValue.Body = new _4_Tell.ws_3dCartApi.runQueryRequestBody();
            inValue.Body.storeUrl = storeUrl;
            inValue.Body.userKey = userKey;
            inValue.Body.sqlStatement = sqlStatement;
            inValue.Body.callBackURL = callBackURL;
            _4_Tell.ws_3dCartApi.runQueryResponse retVal = ((_4_Tell.ws_3dCartApi.cartAPIAdvancedSoap)(this)).runQuery(inValue);
            return retVal.Body.runQueryResult;
        }
    }
}
